name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # ubuntu-20.04

    steps:
      # https://github.com/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v2

      # https://github.com/actions/setup-python
      - name: Install dependencies
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
        run: |
          python -m pip install --upgrade setuptools pip wheel
          python -m pip install tox-gh-actions

      # https://tox.readthedocs.io/en/latest/
      - name: Test with tox
        run: tox

      # https://github.com/actions/upload-artifact
      - name: Upload coverage.xml
        uses: actions/upload-artifact@v2
        with:
          name: tox-gh-actions-coverage
          path: coverage.xml
          if-no-files-found: error


      - name: Upload coverage.xml to codecov
        uses: codecov/codecov-action@v1
